name: Build Plugin Zip File

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: composer:v2

    - name: Build
      run: |
        composer install --quiet --no-dev --optimize-autoloader
        
    - name: Create build archive
      run: ./tools/build_release.sh
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: wp2static
        path: wp2static.zip
        retention-days: 90