name: Build Plugin Zip File

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: composer:v2

    - name: Build
      run: |
        composer install --quiet --no-dev --optimize-autoloader
        
    - name: Create build archive
      run: |
        mkdir -p wp2static
        rsync -r --exclude="LICENSE" --exclude=".git" --exclude=".github" --exclude="integration-tests" --exclude="tests" --exclude="nix" --exclude="tools" --exclude="wp2static" . wp2static/
        find wp2static -type d -exec chmod 755 {} \;
        find wp2static -type f -exec chmod 644 {} \;
        zip --quiet -r -9 wp2static.zip wp2static
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: wp2static
        path: wp2static.zip
        retention-days: 90